name: "notifications"

port:
  grpc: 8083
  http: 8093

loglevel: "info"

cache_size: 128

kafka:
  brokers:
    - "kafka1:29091"
    - "kafka2:29092"
    - "kafka3:29093"
  topic: "notifications"
  group: "group-dev"

telegram:
  token: "TELEGRAM_BOT_TOKEN"
  chat_id: TELEGRAM_CHAT_ID

postgres:
  host: "notifications-postgres-db"
  port: 5432
  user: "postgres"
  password: "password"
  database: "notifications"