version: "3.1"

networks:
  net:
    driver: bridge

volumes:
  checkout_pgdata:
    external: true

  loms_pgdata:
    external: true

services:
  checkout:
    image: checkout
    build: ./checkout/
    ports:
      - "8080:8080"
    depends_on:
      - checkout-postgres-db
    networks:
      - net

  loms:
    image: loms
    build: ./loms/
    ports:
      - "8081:8081"
    depends_on:
      - loms-postgres-db
    networks:
      - net

  # notification:
  #   image: notification
  #   build: ./notification
  #   ports:
  #     - "8082:8082"

  checkout-postgres-db:
    image: postgres:15.1
    environment:
      POSTGRES_DB: checkout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - checkout_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - net

  checkout-pgbouncer:
    image: edoburu/pgbouncer
    environment:
       - DB_USER=postgres
       - DB_PASSWORD=password
       - DB_HOST=checkout-postgres-db
       - DB_NAME=checkout
       - POOL_MODE=transaction
       - AUTH_TYPE=plain
    ports:
      - "5433:5432"
    depends_on:
      - checkout-postgres-db
    networks:
      - net

  loms-postgres-db:
    image: postgres:15.1
    environment:
      POSTGRES_DB: loms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - loms_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - net

  loms-pgbouncer:
    image: edoburu/pgbouncer
    environment:
       - DB_USER=postgres
       - DB_PASSWORD=password
       - DB_HOST=loms-postgres-db
       - DB_NAME=loms
       - POOL_MODE=transaction
       - AUTH_TYPE=plain
    ports:
      - "5434:5432"
    depends_on:
      - loms-postgres-db
    networks:
      - net
