version: "3.1"

networks:
  net:
    driver: bridge

volumes:
  checkout_pgdata:
    external: true

  loms_pgdata:
    external: true

services:
  checkout:
    image: checkout
    build: ./checkout/
    ports:
      - "8080:8080"
    depends_on:
      - checkout-postgres-db
      - kafka1
      - kafka2
      - kafka3
    networks:
      - net

  loms:
    image: loms
    build: ./loms/
    ports:
      - "8081:8081"
    depends_on:
      - loms-postgres-db
      - kafka1
      - kafka2
      - kafka3
    networks:
      - net

  notifications:
    image: notifications
    build: ./notifications/
    ports:
      - "8082:8082"
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  checkout-postgres-db:
    image: postgres:15.1
    environment:
      POSTGRES_DB: checkout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - checkout_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    # ports:
    #   - "5433:5432"
    networks:
      - net

  checkout-pgbouncer:
    image: edoburu/pgbouncer
    environment:
       - DB_USER=postgres
       - DB_PASSWORD=password
       - DB_HOST=checkout-postgres-db
       - DB_NAME=checkout
       - POOL_MODE=transaction
       - AUTH_TYPE=plain
    ports:
      - "5433:5432"
    depends_on:
      - checkout-postgres-db
    networks:
      - net

  loms-postgres-db:
    image: postgres:15.1
    environment:
      POSTGRES_DB: loms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - loms_pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    # ports:
    #   - "5434:5432"
    networks:
      - net

  loms-pgbouncer:
    image: edoburu/pgbouncer
    environment:
       - DB_USER=postgres
       - DB_PASSWORD=password
       - DB_HOST=loms-postgres-db
       - DB_NAME=loms
       - POOL_MODE=transaction
       - AUTH_TYPE=plain
    ports:
      - "5434:5432"
    depends_on:
      - loms-postgres-db
    networks:
      - net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    expose:
      - "2181:2181"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper:2888:3888
    networks:
      - net

  kafka1:
    image: confluentinc/cp-kafka:latest
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
       - zookeeper
    ports:
      - "9091:9091"
    expose:
      - "9091"
    environment:
      - KAFKA_LISTENERS=LISTENER_INT://kafka1:29091,LISTENER_EXT://0.0.0.0:9091
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_INT://kafka1:29091,LISTENER_EXT://localhost:9091
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - ZOOKEEPER=zookeeper:2181
    networks:
      - net

  kafka2:
    image: confluentinc/cp-kafka:latest
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9092"
    environment:
      - KAFKA_LISTENERS=LISTENER_INT://kafka2:29092,LISTENER_EXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_INT://kafka2:29092,LISTENER_EXT://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=2
      - ZOOKEEPER=zookeeper:2181
    networks:
      - net

  kafka3:
    image: confluentinc/cp-kafka:latest
    healthcheck:
      test: ps augwwx | egrep [S]upportedKafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    expose:
      - "9093"
    environment:
      - KAFKA_LISTENERS=LISTENER_INT://kafka3:29093,LISTENER_EXT://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_INT://kafka3:29093,LISTENER_EXT://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INT
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=3
      - ZOOKEEPER=zookeeper:2181
    networks:
      - net