// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "route256/checkout/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// CartItemsRepository is an autogenerated mock type for the CartItemsRepository type
type CartItemsRepository struct {
	mock.Mock
}

type CartItemsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CartItemsRepository) EXPECT() *CartItemsRepository_Expecter {
	return &CartItemsRepository_Expecter{mock: &_m.Mock}
}

// AddToCart provides a mock function with given fields: ctx, user, sku, count
func (_m *CartItemsRepository) AddToCart(ctx context.Context, user int64, sku uint32, count uint16) error {
	ret := _m.Called(ctx, user, sku, count)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uint32, uint16) error); ok {
		r0 = rf(ctx, user, sku, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CartItemsRepository_AddToCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddToCart'
type CartItemsRepository_AddToCart_Call struct {
	*mock.Call
}

// AddToCart is a helper method to define mock.On call
//   - ctx context.Context
//   - user int64
//   - sku uint32
//   - count uint16
func (_e *CartItemsRepository_Expecter) AddToCart(ctx interface{}, user interface{}, sku interface{}, count interface{}) *CartItemsRepository_AddToCart_Call {
	return &CartItemsRepository_AddToCart_Call{Call: _e.mock.On("AddToCart", ctx, user, sku, count)}
}

func (_c *CartItemsRepository_AddToCart_Call) Run(run func(ctx context.Context, user int64, sku uint32, count uint16)) *CartItemsRepository_AddToCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(uint32), args[3].(uint16))
	})
	return _c
}

func (_c *CartItemsRepository_AddToCart_Call) Return(_a0 error) *CartItemsRepository_AddToCart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CartItemsRepository_AddToCart_Call) RunAndReturn(run func(context.Context, int64, uint32, uint16) error) *CartItemsRepository_AddToCart_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCart provides a mock function with given fields: ctx, user
func (_m *CartItemsRepository) DeleteCart(ctx context.Context, user int64) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CartItemsRepository_DeleteCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCart'
type CartItemsRepository_DeleteCart_Call struct {
	*mock.Call
}

// DeleteCart is a helper method to define mock.On call
//   - ctx context.Context
//   - user int64
func (_e *CartItemsRepository_Expecter) DeleteCart(ctx interface{}, user interface{}) *CartItemsRepository_DeleteCart_Call {
	return &CartItemsRepository_DeleteCart_Call{Call: _e.mock.On("DeleteCart", ctx, user)}
}

func (_c *CartItemsRepository_DeleteCart_Call) Run(run func(ctx context.Context, user int64)) *CartItemsRepository_DeleteCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *CartItemsRepository_DeleteCart_Call) Return(_a0 error) *CartItemsRepository_DeleteCart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CartItemsRepository_DeleteCart_Call) RunAndReturn(run func(context.Context, int64) error) *CartItemsRepository_DeleteCart_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFromCart provides a mock function with given fields: ctx, user, sku
func (_m *CartItemsRepository) DeleteFromCart(ctx context.Context, user int64, sku uint32) error {
	ret := _m.Called(ctx, user, sku)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uint32) error); ok {
		r0 = rf(ctx, user, sku)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CartItemsRepository_DeleteFromCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFromCart'
type CartItemsRepository_DeleteFromCart_Call struct {
	*mock.Call
}

// DeleteFromCart is a helper method to define mock.On call
//   - ctx context.Context
//   - user int64
//   - sku uint32
func (_e *CartItemsRepository_Expecter) DeleteFromCart(ctx interface{}, user interface{}, sku interface{}) *CartItemsRepository_DeleteFromCart_Call {
	return &CartItemsRepository_DeleteFromCart_Call{Call: _e.mock.On("DeleteFromCart", ctx, user, sku)}
}

func (_c *CartItemsRepository_DeleteFromCart_Call) Run(run func(ctx context.Context, user int64, sku uint32)) *CartItemsRepository_DeleteFromCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(uint32))
	})
	return _c
}

func (_c *CartItemsRepository_DeleteFromCart_Call) Return(_a0 error) *CartItemsRepository_DeleteFromCart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CartItemsRepository_DeleteFromCart_Call) RunAndReturn(run func(context.Context, int64, uint32) error) *CartItemsRepository_DeleteFromCart_Call {
	_c.Call.Return(run)
	return _c
}

// ListCart provides a mock function with given fields: ctx, user
func (_m *CartItemsRepository) ListCart(ctx context.Context, user int64) ([]*domain.CartItem, error) {
	ret := _m.Called(ctx, user)

	var r0 []*domain.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*domain.CartItem, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*domain.CartItem); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CartItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CartItemsRepository_ListCart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCart'
type CartItemsRepository_ListCart_Call struct {
	*mock.Call
}

// ListCart is a helper method to define mock.On call
//   - ctx context.Context
//   - user int64
func (_e *CartItemsRepository_Expecter) ListCart(ctx interface{}, user interface{}) *CartItemsRepository_ListCart_Call {
	return &CartItemsRepository_ListCart_Call{Call: _e.mock.On("ListCart", ctx, user)}
}

func (_c *CartItemsRepository_ListCart_Call) Run(run func(ctx context.Context, user int64)) *CartItemsRepository_ListCart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *CartItemsRepository_ListCart_Call) Return(_a0 []*domain.CartItem, _a1 error) *CartItemsRepository_ListCart_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CartItemsRepository_ListCart_Call) RunAndReturn(run func(context.Context, int64) ([]*domain.CartItem, error)) *CartItemsRepository_ListCart_Call {
	_c.Call.Return(run)
	return _c
}

// NewCartItemsRepository creates a new instance of CartItemsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartItemsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartItemsRepository {
	mock := &CartItemsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
