port:
  grpc: 8081
  http: 8091

postgres:
  host: "localhost"
  port: 5434
  user: "postgres"
  password: "password"
  database: "loms"

kafka:
  brokers:
    - "127.0.0.1:9091"
		- "127.0.0.1:9092"
		- "127.0.0.1:9093"
  topic: "notifications"